global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: microfi-core
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["microfi-core:8080"]

  - job_name: microfi-middleware
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["microfi-middleware:8081"]
