import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Locale } from "./i18n/dictionaries";

export interface ExportColumn<T> {
  header: string;
  value: (row: T) => string | number;
}

export interface ExportMeta {
  scope: string; // e.g. a branch name, or "All branches"
  from?: string; // ISO date, "2026-08-01" — omit for a live-snapshot export with no natural period (e.g. a directory listing)
  to?: string; // ISO date, "2026-09-01"
  generatedBy: string; // admin login
  locale: Locale; // the platform's current locale — the generated document follows it, not the browser's
}

const LOCALE_TAG: Record<Locale, string> = { en: "en-US", fr: "fr-FR" };

// Self-contained rather than pulled from the app's Dictionary: these are the only strings this
// module needs, and pulling in the full Dictionary type here would drag a server-only-guarded
// module into client bundles that use export.ts.
const LABELS: Record<Locale, { scope: string; period: string; periodSeparator: string; generatedAt: string; generatedBy: string; internalOfficer: string; externalAuditor: string }> = {
  en: {
    scope: "Scope",
    period: "Period",
    periodSeparator: "to",
    generatedAt: "Generated at",
    generatedBy: "Generated by",
    internalOfficer: "Internal Compliance Officer",
    externalAuditor: "External Auditor",
  },
  fr: {
    scope: "Portée",
    period: "Période",
    periodSeparator: "au",
    generatedAt: "Généré le",
    generatedBy: "Généré par",
    internalOfficer: "Responsable Conformité Interne",
    externalAuditor: "Auditeur Externe",
  },
};

/** Null when the export has no natural period (e.g. a directory listing) — the caller then omits the "Period" line entirely rather than printing an empty/misleading range. */
function formatPeriod(meta: ExportMeta): string | null {
  if (!meta.from || !meta.to) return null;
  const labels = LABELS[meta.locale];
  return `${meta.from} ${labels.periodSeparator} ${meta.to}`;
}

/** Real, verifiable .xlsx export (SheetJS): a metadata block on top, then the data table. */
export function exportToExcel<T>(filename: string, sheetName: string, meta: ExportMeta, columns: ExportColumn<T>[], rows: T[]) {
  const labels = LABELS[meta.locale];
  const period = formatPeriod(meta);
  const metaRows: (string | number)[][] = [
    [`MICROFI: ${sheetName}`],
    [labels.scope, meta.scope],
    ...(period ? [[labels.period, period]] : []),
    [labels.generatedAt, new Date().toLocaleString(LOCALE_TAG[meta.locale])],
    [labels.generatedBy, meta.generatedBy],
    [],
  ];
  const headerRow = columns.map((c) => c.header);
  const dataRows = rows.map((row) => columns.map((c) => c.value(row)));
  const worksheet = XLSX.utils.aoa_to_sheet([...metaRows, headerRow, ...dataRows]);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName.slice(0, 31));
  XLSX.writeFile(workbook, `${filename}.xlsx`);
}

/**
 * Compliance-style PDF export mirroring the reference COBAC audit report's shape: a dark navy
 * header banner, a metadata box, the data table, and two blank signature lines a compliance
 * officer/external auditor can actually print and sign.
 */
export function exportToPdf<T>(filename: string, title: string, meta: ExportMeta, columns: ExportColumn<T>[], rows: T[]) {
  const labels = LABELS[meta.locale];
  const doc = new jsPDF({ orientation: columns.length > 5 ? "landscape" : "portrait" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFillColor(15, 30, 60);
  doc.rect(0, 0, pageWidth, 24, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("MICROFI", 14, 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(title, 14, 19);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(9);
  let y = 32;
  const period = formatPeriod(meta);
  for (const line of [
    `${labels.scope}: ${meta.scope}`,
    ...(period ? [`${labels.period}: ${period}`] : []),
    `${labels.generatedAt}: ${new Date().toLocaleString(LOCALE_TAG[meta.locale])}`,
    `${labels.generatedBy}: ${meta.generatedBy}`,
  ]) {
    doc.text(line, 14, y);
    y += 5;
  }

  autoTable(doc, {
    startY: y + 3,
    head: [columns.map((c) => c.header)],
    body: rows.map((row) => columns.map((c) => String(c.value(row)))),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [15, 30, 60] },
  });

  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;

  let sigY = finalY + 20;
  if (sigY > pageHeight - 25) {
    doc.addPage();
    sigY = 30;
  }
  doc.setDrawColor(120, 120, 120);
  doc.line(14, sigY, 90, sigY);
  doc.line(pageWidth - 82, sigY, pageWidth - 14, sigY);
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);
  doc.text(labels.internalOfficer, 14, sigY + 5);
  doc.text(labels.externalAuditor, pageWidth - 82, sigY + 5);

  doc.save(`${filename}.pdf`);
}
